### PR TITLE
Bump to 3.18.0 and enable Windows build.

### PR DESCRIPTION
**Pull request by seanyen**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by seanyen** [comment]
cc @almarklein @jakirkham @msarahan @wolfv

**Comment by seanyen** [comment]
Hope this address this request: #7

**Comment by wolfv** [comment]
definitely adresses my request. This is a pretty big deal in my opinion! Thanks for working on this.

**Comment by seanyen** [comment]
@almarklein @jakirkham @msarahan Let me know if anything I should iterate on this pull request. I am also adding myself as a co-maintainer. Thanks!

**Comment by almarklein** [comment]
> I am also adding myself as a co-maintainer

That's great!

**Pull request merged**
